# Turn on RSpec cops
require: rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Include:
    - './Rakefile'
    - '**/*.rb'

Capybara/FeatureMethods:
  EnabledMethods:
    - 'scenario'

RSpec/ExampleLength:
  Exclude:
    - 'spec/features/*.rb'

RSpec/MultipleExpectations:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods:
    - describe
    - it
    - context
    - scenario

Style/IfInsideElse:
  Exclude:
    - 'spec/support/page_helpers.rb'
