timeouts:  # in seconds
  capybara: 60
  workflow: 300
  bulk_action: 200
  post_authentication_text: 5
  h2_terms_modal_wait: 5 # should show quickly, so can be much shorter than default wait time
  events:
    poll_for: 240
    poll_interval: 2

browser:
  driver: firefox
  height: 900
  width: 1440

default_apo: 'druid:qc410yz8746'
default_collection: 'druid:bc778pm9866'

# For virtual object testing
number_of_constituents: 2

supported_envs:
  - qa
  - stage

etd:
  username: ~
  password: ~

# for dor-services-client (e.g. to get public_xml from dor-services-app)
# See README for instructions
dor_services:
  token: ~

sunet:
  id: ~ # NOTE: *without* @stanford.edu!
  password: ~

# the URL and username/password used to login to goobi (applicable to stage only)
goobi:
  url: https://goobi-stage-a.stanford.edu/goobi
  username: ~
  password: ~

gis:
  robots_content_root: '/gis_workflow_data/stage'

test_folio_instance_hrid: 'a10065784'

# note for purl_url: there is no purl for qa;  sul-h2-qa uses stage ...
purl_url: 'https://sul-purl-stage.stanford.edu' # from shared_configs for sul-h2-stage
preassembly:
  username: 'preassembly'
  bundle_directory: '/dor/staging/integration-tests/files-reaccessioning-test'
  hfs_bundle_directory: '/dor/staging/integration-tests/hierarchical-file-test'
  gis_bundle_directory: '/dor/staging/integration-tests/gis-test'
