timeouts:
  capybara: 60
  workflow: 300
  bulk_action: 200
  events:
    poll_for: 240
    poll_interval: 2


browser:
  driver: firefox
  height: 900
  width: 1440

default_apo: 'druid:qc410yz8746'
default_collection: 'druid:bc778pm9866'

automatic_authentication: false
post_authentication_text_timeout: 5 # in seconds

etd:
  username: ~
  password: ~

# for calls to dor-services-app (not using dor-services-client directly)
# note that this token is the same as below ...
dor_services_app:
  token: ~

# for direct use of dor-services-client (e.g. to get public_xml from dor-services-app)
# note that this token is the same as above ...
dor_services:
  token: ~

sunet:
  id: ~ # NOTE: *without* @stanford.edu!
  password: ~
