etd:
  username: ~
  password: ~

timeouts:
  capybara: 60
  workflow: 300
  bulk_action: 200

sunet:
  id: ~ # NOTE: *without* @stanford.edu!
  password: ~

browser:
  driver: firefox
  height: 900
  width: 1440

default_apo: 'druid:qc410yz8746'
default_collection: 'druid:bc778pm9866'

automatic_authentication: false
