argo_url: 'https://argo-stage.stanford.edu'
dor_services:
  url: 'https://dor-services-stage.stanford.edu'
etd_url: 'https://etd-stage.stanford.edu'
h2_url: 'https://sul-h2-stage.stanford.edu'
purl_url: 'https://sul-purl-stage.stanford.edu' # from shared_configs for sul-h2-stage
preassembly_bundle_directory: '/dor/staging/integration-tests/image-test'
preassembly_host: 'sul-preassembly-stage'
preassembly_url: 'https://sul-preassembly-stage.stanford.edu'
sdrapi_url: 'https://sdr-api-stage.stanford.edu'
